### ISSUE TITLE
Let's Encrypt certificate not renewing on campr.cloud

### ISSUE THREAD

**Issue by paulocoghi** [Campr-Project-Management/campr#153]
First of all, congratulations on the excellent software.

I would just like to inform the Let's Encrypt certificate on campr.cloud expired and it seems the auto-renew isn't properly configured.

I take this opportunity to suggest the use of TLS 1.3 on your servers. It's faster, use fewer CPU resources and more secure.

Thanks again!

**Comment by cristobalcampr** [comment]
> First of all, congratulations on the excellent software.
> 
> I would just like to inform the Let's Encrypt certificate on campr.cloud expired and it seems the auto-renew isn't properly configured.
> 
> I take this opportunity to suggest the use of TLS 1.3 on your servers. It's faster, use fewer CPU resources and more secure.
> 
> Thanks again!

Thanks Paulo for informing, issue solved:)
